

# SPECIALS

TOKEN_PAD='<pad>'
TOKEN_UNKOWN='<unk>'
TOKEN_BOS='<s>'  # of sentence
TOKEN_EOS='</s>'
TOKEN_BOQ='<q>'   # of question
TOKEN_EOQ='</q>'
TOKEN_BOA = '<a>'  # of answer
TOKEN_EOA = '</a>'
TOKEN_BOC='<c>'   # of context
TOKEN_EOC='</c>'

TOKEN_MASK='<mask>'
TOKEN_FAKE='<fake>'
TOKEN_HARMONY='<real>'

TOKEN_SELF='<self>'
TOKEN_QUESTION='<question>'
TOKEN_ANSWER='<answer>'
TOKEN_CONTEXT='<context>'
TOKEN_CLS='<cls>'
TOKEN_QA='<qa>'
TOKEN_TRANSLATE='<trans>'

BODY_SINGLE=0
BODY_HEAD=1
BODY_TAIL=2
BODY_MIDDLE=3

TASK_SELF=0
TASK_QA=1
TASK_TRANSLATE = 2

SCORE_MASK="SCORE_MASK"
SCORE_CHAR="SCORE_CHAR"
SCORE_WORD="SCORE_WORD"
SCORE_MODIFY="SCORE_MODIFY"
SCORE_RELATION="SCORE_RELATION"
SCORE_QA="SCORE_QA"


